---
title: "<Assignment 2> Importing and Playing with Excel File in R, Due 09/22/2024"
author: "so518@scarletmail.rutgers.edu"
date: "9/21/2024"
output: html_document
---
```{r}

library(readxl)
Typical_Employee_Survey_Data<-read_excel("/Users/suminoh/Downloads/Typical_Employee_Survey_Data.xlsx",col_names = FALSE)



Typical_Employee_Survey_Data
```


### 1. Add Header Row (10 points)
```{r}
new_header<-c("age","gender","Job Satisfaction","Important Character","Service Year","Promotion Possibility","Decision Participation","Budgetary Decisions","Pride","Loyalty","Coworker Relationship")

colnames(Typical_Employee_Survey_Data)<-new_header

Typical_Employee_Survey_Data
```

### 2. Print out the 5-point summary and boxplot (numerical columns) for each column (20 points)
```{r}
boxplot(Typical_Employee_Survey_Data,las=2,main="Box Plot by Category")
summary(Typical_Employee_Survey_Data)
```

### 3. Convert the columns that need to be converted to Factors (10 points)
```{r}
str(Typical_Employee_Survey_Data)

Typical_Employee_Survey_Data$gender<-factor(Typical_Employee_Survey_Data$gender)
Typical_Employee_Survey_Data$`Job Satisfaction`<-factor(Typical_Employee_Survey_Data$`Job Satisfaction`)
Typical_Employee_Survey_Data$`Important Character`<-factor(Typical_Employee_Survey_Data$`Important Character`)
Typical_Employee_Survey_Data$`Promotion Possibility`<-factor(Typical_Employee_Survey_Data$`Promotion Possibility`)
Typical_Employee_Survey_Data$`Decision Participation`<-factor(Typical_Employee_Survey_Data$`Decision Participation`)
Typical_Employee_Survey_Data$`Budgetary Decisions`<-factor(Typical_Employee_Survey_Data$`Budgetary Decisions`)
Typical_Employee_Survey_Data$Pride<-factor(Typical_Employee_Survey_Data$Pride)
Typical_Employee_Survey_Data$Loyalty<-factor(Typical_Employee_Survey_Data$Loyalty)
Typical_Employee_Survey_Data$`Coworker Relationship`<-factor(Typical_Employee_Survey_Data$`Coworker Relationship`)

str(Typical_Employee_Survey_Data)
```

### 4. Plot the right visual for each column (20 points)
```{r}

# Age
hist(Typical_Employee_Survey_Data$age,main="Employee Age")

# Gender
gender_freq<-table(Typical_Employee_Survey_Data$gender)
pie(gender_freq,main="Gender Distribution",labels = c("Male","Female"))

# Job Satisfaction
JS_freq<-table(Typical_Employee_Survey_Data$`Job Satisfaction`)
pie(JS_freq,main="Job Satisfaction",labels=c("Very Satisfied", "Moderately Satisfied", "A little Dissatisfied", "Very Dissatisfied"))

# Important job character
imp_freq<-table(Typical_Employee_Survey_Data$`Important Character`)
pie(imp_freq,main="Important job characteristics",labels=c("High Income","No Danger of Being Fired","Flexible Hours","Opportunities for Advancement","Enjoying the Work"))

# Service Year
plot(density(Typical_Employee_Survey_Data$`Service Year`), main = "Density of Service Years", xlab = "Service Years")

# Promotion Possibility
promo_freq<-table(Typical_Employee_Survey_Data$`Promotion Possibility`)

bp<-barplot(promo_freq,names.arg=c("Very Likely","Likely","Not Sure","Unlikely","Very Unlikely"),ylab="frequency",main="Promotion Possibility")
text(x=bp,y=promo_freq-1,labels=promo_freq, cex=0.8)

# Decision Participation
dec_freq<-table(Typical_Employee_Survey_Data$`Decision Participation`)
pie(dec_freq,main="Decision Participation level",labels=c("Always","Much of the Time","Sometimes","Never"))

#Budgetary Decisions
budget_freq<-table(Typical_Employee_Survey_Data$`Budgetary Decisions`)
barplot(budget_freq,names.arg=c("Yes","No"),main="Budgetary Decisions participation")

#Pride
pride_freq<-table(Typical_Employee_Survey_Data$Pride)
barplot(pride_freq,main="Pride to work",names.arg=c("Very Proud","Somewhat Proud","Indifferent","Not At All Proud"))

#Loyalty
loyalty_freq<-table(Typical_Employee_Survey_Data$Loyalty)
pie(loyalty_freq,labels=c("Very Likely","Likely","Not Sure","Unlikely","Very Unlikely"),main="Would you turn down another job for more pay to stay?")

#Coworker relationship
coworker_freq<-table(Typical_Employee_Survey_Data$`Coworker Relationship`)
barplot(coworker_freq,main="Coworker Relationship")

```

### 5. Plot scatter plots to show few relationships (20 points)

```{r}
options(repos = c(CRAN = "https://cloud.r-project.org"))
if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2)

ggplot(Typical_Employee_Survey_Data, aes(x=`Job Satisfaction`, y=Loyalty)) + geom_point(alpha=0.5) + labs(title="Scatter Plot of Job Satisfaction vs Loyalty", x="Job Satisfaction",y="Loyalty")


ggplot(Typical_Employee_Survey_Data, aes(x=`Job Satisfaction`, y=`Coworker Relationship`)) + geom_point(alpha=0.5) + labs(title="Scatter Plot of Job Satisfaction vs Coworker Relationship", x="Job Satisfaction",y="Coworker Relationship")

```
